### ISSUE TITLE
Using  responsive param created "Cannot read property 'length' of null" error

### ISSUE THREAD

**Issue by sshadmand** [katspaugh/wavesurfer.js#1507]
### Wavesurfer.js version(s):

```"wavesurfer.js": "^2.0.5",```

### Browser version(s):

Mac Chrome 70

### Code needed to reproduce the issue:
Using React, I load the below code. I noticed that the error only occurs with `responsive: true`. Commenting it out works cleanly.

```
this.wavesurfer = WaveSurfer.create({
        container: this.el,
        waveColor: color,
        progressColor: color,
        cursorColor: '#5173E7',
        cursorWidth: 3,
        barWidth: 1,
        responsive: true,
        height,
        audioRate
      })
```

Error it produces in console
```
Uncaught TypeError: Cannot read property 'length' of null
    at t.value (wavesurfer.min.js:6)
    at t.value (wavesurfer.min.js:6)
    at wavesurfer.min.js:6
    at wavesurfer.min.js:6
    at Array.forEach (<anonymous>)
    at t.value (wavesurfer.min.js:6)
    at wavesurfer.min.js:6
    at n (wavesurfer.min.js:6)
    at wrapped (index.js:3221)
value @ wavesurfer.min.js:6
value @ wavesurfer.min.js:6
(anonymous) @ wavesurfer.min.js:6
(anonymous) @ wavesurfer.min.js:6
value @ wavesurfer.min.js:6
(anonymous) @ wavesurfer.min.js:6
n @ wavesurfer.min.js:6
wrapped @ index.js:3221
setTimeout (async)
(anonymous) @ index.js:3430
l @ wavesurfer.min.js:6
wrapped @ index.js:3221
```

**Comment by thijstriemstra** [comment]
you're passing it an invalid oject:

```javascript
var invalid = {
        container: this.el,
        waveColor: color,
        progressColor: color,
        cursorColor: '#5173E7',
        cursorWidth: 3,
        barWidth: 1,
        responsive: true
        height, // hello?!
        audioRate
      }
```

**Comment by sshadmand** [comment]
A bit vague. What is invalid about it. All those parameters are in the docs and it works sans the responsive flag.

**Comment by thijstriemstra** [comment]
if you do not recognize that as a broken JS object, I don't know what to say.

**Comment by clndwhr** [comment]
Sshadman don't forget to separate your objects with commas which is why commenting out your responsive object works; even though it is overall still an invalid js object as it is displayed in your copied code

**Comment by sshadmand** [comment]
Sorry - I have lint, that was a copy paste mistake. Same error with the comma

**Comment by sshadmand** [comment]
It’s been happing for a month and the system wouldn’t commit or compile without the comma. GH thread typo from income ring in GH comment

**Comment by clndwhr** [comment]
Using the same parameters you have I'm getting object errors on the height and audiorate and container,  Fixing it to have a height:100, and audioRate:1,  assigning container: '#<div> resolved all issues while still rendering with responsive:true.  I can even test this in MacOS Chrome though.  

Do assigning those values change anything?

**Comment by sshadmand** [comment]
Hey guys- this is my fault. I was lazy with my copy paste and could be clearer (e.g. not showing the param values and using condensed express format) Let me get a more rich description (in/out) and help y’all help me :-)

**Comment by sshadmand** [comment]
**Update**

As you can see from the image below, I printed to the console the variables passed into the wavesurfer create. Also, you can see the error that is produced, even with the wave loading just fine. Removing `        responsive: true`  works without an error at all.


<img width="1406" alt="screen shot 2018-11-15 at 10 49 46 pm" src="https://user-images.githubusercontent.com/68735/48596971-57287400-e929-11e8-9e07-7f9b33b383e5.png">

```
import React, { Component } from 'react'
import styled from 'styled-components'
import WaveSurfer from './WaveSurfer'

const Root = styled.div`
  width: 100%;
  display: flex;
  align-items: center;
`

const AudioWave = styled.div`
  flex: 1;
`

const TimeStamp = styled.div`
  flex: 0;
  padding: 0 16px;
  font-size: 0.8em;
  color: rgba(0,0,0,0.5);
`

class Wave extends Component {
  state = {}

  init = () => {
    const {muted, url, color, height, onSeek, audioRate, onLoading} = this.props

    if (url && this.url !== url && this.el) {
      this.url = url
      const waveParams = {
        container: this.el,
        waveColor: color,
        progressColor: color,
        cursorColor: '#5173E7',
        cursorWidth: 3,
        barWidth: 1,
        responsive: true,
        height,
        audioRate
      }
      console.log(waveParams)
      this.wavesurfer = WaveSurfer.create(waveParams)

      if (muted) {
        this.wavesurfer.setMute(true)
      }
      this.wavesurfer.load(url)
      onSeek && this.wavesurfer.on('seek', onSeek)
      this.wavesurfer.on('ready', this.handleOnReady)
      this.wavesurfer.on('audioprocess', this.handleOnAudioprocess)
      onLoading && this.wavesurfer.on('loading', onLoading)
      // console.log('re-Loaded', this.wavesurfer, url)
    }
  }

  componentWillReceiveProps = () => this.init()

  componentDidMount = () => this.init()

  componentWillUnmount = () => this.wavesurfer && this.wavesurfer.destroy()

  getFormattedTime = (time) => {
    return [
      Math.floor((time % 3600) / 60), // minutes
      ('00' + Math.floor(time % 60)).slice(-2) // seconds
    ].join(':')
  }

  handleOnReady = (evt) => {
    this.setState({
      timeStamp: this.getFormattedTime(this.getDuration() - this.wavesurfer.getCurrentTime())
    })

    this.props.onReady && this.props.onReady(evt)
  }

  handleOnAudioprocess = (evt) => {
    const timeStamp = this.getFormattedTime(this.getDuration() - this.wavesurfer.getCurrentTime())
    timeStamp !== this.state.timeStamp && this.setState({ timeStamp })
  }

  onEnd = (cb) => this.wavesurfer && this.wavesurfer.on('finish', cb, false)

  unEnd = (cb) => this.wavesurfer && this.wavesurfer.un('finish', cb, false)

  unAll = () => this.wavesurfer && this.wavesurfer.unAll()

  isPlaying = () => (this.wavesurfer && this.wavesurfer.isPlaying())

  play = () => this.wavesurfer && this.wavesurfer.play()

  getCurrentTime = () => (this.wavesurfer && this.wavesurfer.getCurrentTime())

  setMute = (mute) => this.wavesurfer && this.wavesurfer.setMute(mute)

  pause = () => this.wavesurfer && this.wavesurfer.pause()

  stop = () => this.wavesurfer && this.wavesurfer.stop()

  getDuration = () => this.wavesurfer && this.wavesurfer.getDuration()

  setPlaybackRate = (speed) => this.wavesurfer && this.wavesurfer.setPlaybackRate(speed)

  seek = (seekTime) => {
    if (this.getDuration() <= 0) return
    const seekTo = seekTime / this.getDuration()
    this.wavesurfer.seekTo(seekTo)
  }

  render = () => {
    const {className} = this.props
    const {timeStamp} = this.state
    return (
      <Root>
        <TimeStamp>{timeStamp}</TimeStamp>
        <AudioWave
          innerRef={el => (this.el = el)}
          className={className}
        />
      </Root>
    )
  }
}

Wave.defaultProps = {
  onSeek: () => null,
  onReady: () => null,
  height: 80,
  color: '#c2c2c2'
}

export default Wave
```

**Comment by clndwhr** [comment]
@sshadmand  Have you tried passing in the default value?  responsive:100  ?

**Comment by darrenmothersele** [comment]
I get this error when I use the responsive option, but only when I resize the window before I have loaded audio.
This is an edge case that does happen. A window resize event can happen in between creating the WaveSurfer object, and loading the first audio file.

**Comment by thijstriemstra** [comment]
#1529 should fix this.

**Comment by sshadmand** [comment]
FYI for those still experiencing an issue with responsive. 
Using  `responsive: true` no longer pushes an error to the console, but it often does not render the waveform. Removing the `responsive: true` the waveform every time. So, something may be slipping by.
