### ISSUE TITLE
Update wavesurfer's progress when progress changed using HTML controls

### ISSUE THREAD

**Issue by MichalSzorad** [katspaugh/wavesurfer.js#1535]
### Description:
When using WaveSurfer with backend `MediaElement`, the progress is not updated when audio is paused and user changed the progress using HTML controls.

### Expected behaviour:
When using `MediaElement` and the audio (or video) is paused and the user changes progress using HTML controls, the wavesurfer should update it's own progress.

### Wavesurfer.js version(s):
2.1.1

### Browser version(s):
Chrome v71

### Code needed to reproduce the issue:
```js
var ws = WaveSurfer.create({
  container: '#waveform',
  backend: 'MediaElement',
  mediaType: 'audio',
  mediaControls: true,
});

ws.load(document.querySelector('audio'));
```

https://codepen.io/michalszorad/pen/WLxqJv

### Use behaviour needed to reproduce the issue:
Go to codepen link, change the progress using HTML controls and see that the wavesurfer's progress has not updated.

**Comment by thijstriemstra** [comment]
Can not reproduce this on FF64, latest OSX. Haven't tried Chrome.

**Comment by uhoh-itsmaciek** [comment]
I can reproduce this on both latest Chrome and FF in Windows 10: the progress does not update until the audio is resumed. Does onSeek fire when playback is paused?

**Comment by thijstriemstra** [comment]
@MichalSzorad @uhoh-itsmaciek I think I fixed this in PR #1606, can you give that a try?

**Comment by uhoh-itsmaciek** [comment]
Thanks! I'll check this later this week.

**Comment by uhoh-itsmaciek** [comment]
Sorry for the delay. Just checked as of 72b06d09fc86742985b5fa850dc332d0f868c1ac and the problem is not fixed and in fact playback progress no longer updates for me on the histogram when I control playback using the media element controls. Did I miss some breaking changes in configuration in 3.0.0? My setup is pretty simple:

```javascript
    const wavesurfer = WaveSurfer.create({
      backend: 'MediaElement',
      container: '#waveform',
    })
    wavesurfer.load(audioElement)
```

where `#waveform` is just `<div id='waveform' />`. The audio is actually loaded through Howl because I'm depending on some of its functionality, but that shouldn't matter, right?

**Comment by thijstriemstra** [comment]
>  playback progress no longer updates for me on the histogram when I control playback using the media element controls.

histogram? that might be a completely different issue. you shouldn't test fixes with howler or histogram, does it work with normal wavesurfer.js usage, same as you reported. It looks fixed here.

**Comment by thijstriemstra** [comment]
The fix in #1606 wasn't sufficient, re-opening this.

**Comment by thijstriemstra** [comment]
it should probably use `getCurrentTime()` and `seeked` instead..

```javascript
media.addEventListener('seeked', event => {
    this.fireEvent('audioprocess', this.getCurrentTime());
});
```

**Comment by thijstriemstra** [comment]
@uhoh-itsmaciek can you give #1631 a try?

**Comment by uhoh-itsmaciek** [comment]
Sorry, I misspoke: by "histogram" I meant the waveform visualization. This does seem to work.
