### ISSUE TITLE
spectrogram plugin not working

### ISSUE THREAD

**Issue by vim-zz** [katspaugh/wavesurfer.js#606]
the example is broken:http://wavesurfer-js.org/example/spectrogram/

from what i see on init the plug assign:
    
     this.buffer = this.wavesurfer.backend.buffer;

but at that point this.wavesurfer.backend does not have a buffer object.

**Comment by vim-zz** [comment]
i checked the example with more browsers:
- safari - broken
- chrome -broken
- firefox - ok

**Comment by katspaugh** [comment]
cc @akreal

**Comment by akreal** [comment]
Thanks, I'll take a look at it in a week or two.

**Comment by katspaugh** [comment]
@vim-zz please confirm that the PR above solved the problem (it's in master).

**Comment by vim-zz** [comment]
still broken.

on **firefox** it is ok (same as before)

on **safari** i get the following error:
TypeError: undefined is not a constructor (evaluating 'new window.OfflineAudioContext(1, buffer.length, buffer.sampleRate)')
getFrequencieswavesurfer.spectrogram.js:139

on **chrome** i get no error, but the spectrogram image is faultily: 
<img width="572" alt="screen shot 2016-01-15 at 14 11 05" src="https://cloud.githubusercontent.com/assets/50141/12352791/e19ea8fc-bb91-11e5-85ef-306545fd1c1d.png">

**Comment by katspaugh** [comment]
Yes, I get the same exception.

**Comment by akreal** [comment]
Alright, I will try to figure it out.

**Comment by katspaugh** [comment]
@akreal thank you! Safari probably needs the `webkit` prefix like here: https://github.com/katspaugh/wavesurfer.js/blob/master/src/webaudio.js#L25

**Comment by akreal** [comment]
Thanks for your advice @katspaugh. I implemented it, but have no Safari to check if it works.

**Comment by vim-zz** [comment]
@akreal i tried on chrome and safari, still getting same result.

on safari i get the following error:
createScriptProcessorwavesurfer.spectrogram.js:142
IndexSizeError: DOM Exception 1: Index or size was negative, or greater than the allowed value.

on chrome, there is no error the result is not as expected

**Comment by akreal** [comment]
Thank you @vim-zz.
I've added one more workaround for Safari, could you please try now?
Regarding bad image In Chrome, unfortunately this is expected. `OfflineAudioContext` is very unstable in Chrome (and probably in Safari) and this can not be fixed.

**Comment by katspaugh** [comment]
I've merged the fix into master.

**Comment by katspaugh** [comment]
Looks like it's fixed now. It doesn't throw the exception in Safari anymore. Thanks, guys!

**Comment by nuthinking** [comment]
I am not using Wavesurfer but I am trying to analyze in the background the waveform with an offline context and I am having issues with Safari too. The latest version of Wavesurfer doesn't seem to use the suggested workaround anymore. I wonder if someone here can point me to the latest workaround for this issue. Thanks!

[Question in Stackoverflow](https://stackoverflow.com/questions/46621954/offlineaudiocontext-and-background-waveform-analysis-in-safari)
